// <auto-generated />
using System;
using ApiReservaTurnos.Persistencia.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiReservaTurnos.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20231110055945_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiReservaTurnos.Domain.Models.Comercio", b =>
                {
                    b.Property<int>("id_comercio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("aforo_maximo")
                        .HasColumnType("int");

                    b.Property<string>("nom_comercio")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_comercio");

                    b.ToTable("Comercio");
                });

            modelBuilder.Entity("ApiReservaTurnos.Domain.Models.Servicio", b =>
                {
                    b.Property<int>("id_Servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("duracion")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("hora_apertura")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("hora_cierre")
                        .HasColumnType("time");

                    b.Property<int>("id_Comercio")
                        .HasColumnType("int");

                    b.Property<string>("nom_servicio")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("id_Servicio");

                    b.HasIndex("id_Comercio");

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("ApiReservaTurnos.Domain.Models.Turnos", b =>
                {
                    b.Property<int>("id_turno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_turno")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("hora_fin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("hora_inicio")
                        .HasColumnType("time");

                    b.Property<int>("id_servicio")
                        .HasColumnType("int");

                    b.HasKey("id_turno");

                    b.HasIndex("id_servicio");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("ApiReservaTurnos.Domain.Models.Servicio", b =>
                {
                    b.HasOne("ApiReservaTurnos.Domain.Models.Comercio", "Comercio")
                        .WithMany("Servicio")
                        .HasForeignKey("id_Comercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("ApiReservaTurnos.Domain.Models.Turnos", b =>
                {
                    b.HasOne("ApiReservaTurnos.Domain.Models.Servicio", "Servicio")
                        .WithMany("Turnos")
                        .HasForeignKey("id_servicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ApiReservaTurnos.Domain.Models.Comercio", b =>
                {
                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ApiReservaTurnos.Domain.Models.Servicio", b =>
                {
                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
